services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: lip_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - lip-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: lip-pgadmin
    depends_on:
      - postgres
    environment:
      # Credenciais para logar na TELA do pgAdmin (não é a do banco)
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80" # Você acessará em http://localhost:5050
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - lip-network

  backend:
    build: ./
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lip_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - lip-network

volumes:
  postgres_data:
  pgadmin_data:


networks:
  lip-network:
    driver: bridge
