services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USER}'
    ports:
      - '5432'
  pg_admin:
    image: 'dpage/pgadmin4:latest'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}'
      - 'PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}'
    ports:
      - '8081:80'
    depends_on:
      - postgres
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: lip-backend:latest
    ports:
      - '8080:8080'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_NAME}'
      - 'SPRING_DATASOURCE_USERNAME=${DB_USER}'
      - 'SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}'
      - 'SPRING_PROFILES_ACTIVE=dev'
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local